volumes:
  psql:
  pgadmin:

services:
  psql:
    image: postgres
    restart: always
    volumes:
      - psql:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: m35pn92x

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - 10001:80
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@mail.com
      - PGADMIN_DEFAULT_PASSWORD=m35pn92x
      - POSTGRES_DB=Paraglider
    depends_on:
      - psql

  paraglider_app:
    image: maxxlorge/paraglider:latest
    restart: always
    ports:
      - 5000:80
    environment:
      - TZ=Asia/Yekaterinburg
      - ConnectionStrings:PostgreSQL=Server=psql;Database=Paraglider;Username=postgres;Password=m35pn92x;Pooling=true;
    depends_on:
      - psql