volumes:
  mongo-db-1:
  mongo-db-2:
  psql:
  pgadmin:

services:
  mongo:
    image: mongo
    restart: always
    volumes:
      - mongo-db-1:/data/db
      - mongo-db-2:/data/configdb
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: m35pn92x
    ports:
      - 27017:27017

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: m35pn92x
      ME_CONFIG_MONGODB_URL: mongodb://root:m35pn92x@mongo:27017/
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: m35pn92x
    depends_on:
      - mongo
  
  psql:
    image: postgres
    restart: always
    volumes:
      - psql:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: m35pn92x

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - 10001:80
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@mail.com
      - PGADMIN_DEFAULT_PASSWORD=m35pn92x
    depends_on:
      - psql

  paraglider_app:
    image: maxxlorge/paraglider:latest
    restart: always
    environment:
      - TZ=Asia/Yekaterinburg
      - ConnectionStrings:MongoDB=mongodb://root:m35pn92x@mongo:27017/
      - ConnectionStrings:PostgreSQL=Server=psql;Username=postgres;Password=m35pn92x;Pooling=true;
    depends_on:
      - psql
      - mongo
  
  nginx:
    image: nginx
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - paraglider_app