//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

module Paraglider.API.Features.Authorization.Commands {
	export class BasicAuthRequest
	{
		public Login: string;
		public Password: string;
	}
	export class LogoutRequest
	{
	}
}
