// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Paraglider.AspNetCore.Identity.Domain;

#nullable disable

namespace Paraglider.AspNetCore.Identity.Domain.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Paraglider.AspNetCore.Identity.Domain.Entities.Album", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Albums");
                });

            modelBuilder.Entity("Paraglider.AspNetCore.Identity.Domain.Entities.ApplicationRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Paraglider.AspNetCore.Identity.Domain.Entities.ApplicationUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<Guid>("CityId")
                        .HasColumnType("uuid");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Paraglider.AspNetCore.Identity.Domain.Entities.BanquetHall", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AlbumId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CityId")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("WeddingPlanId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AlbumId");

                    b.HasIndex("CityId");

                    b.HasIndex("WeddingPlanId");

                    b.ToTable("BanquetHalls");
                });

            modelBuilder.Entity("Paraglider.AspNetCore.Identity.Domain.Entities.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("WeddingPlanId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("WeddingPlanId");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("Paraglider.AspNetCore.Identity.Domain.Entities.Catering", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AlbumId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CityId")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("WeddingPlanId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AlbumId");

                    b.HasIndex("CityId");

                    b.HasIndex("WeddingPlanId");

                    b.ToTable("Caterings");
                });

            modelBuilder.Entity("Paraglider.AspNetCore.Identity.Domain.Entities.City", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Cities");
                });

            modelBuilder.Entity("Paraglider.AspNetCore.Identity.Domain.Entities.Decorator", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AlbumId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CityId")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("WeddingPlanId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AlbumId");

                    b.HasIndex("CityId");

                    b.HasIndex("WeddingPlanId");

                    b.ToTable("Decorators");
                });

            modelBuilder.Entity("Paraglider.AspNetCore.Identity.Domain.Entities.Dj", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AlbumId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CityId")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("WeddingPlanId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AlbumId");

                    b.HasIndex("CityId");

                    b.HasIndex("WeddingPlanId");

                    b.ToTable("Djs");
                });

            modelBuilder.Entity("Paraglider.AspNetCore.Identity.Domain.Entities.Limousine", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AlbumId")
                        .HasColumnType("uuid");

                    b.Property<int?>("Capacity")
                        .HasColumnType("integer");

                    b.Property<Guid>("CityId")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ManufactureYear")
                        .HasColumnType("timestamp with time zone");

                    b.Property<TimeSpan?>("MinRentLength")
                        .HasColumnType("interval");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("WeddingPlanId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AlbumId");

                    b.HasIndex("CityId");

                    b.HasIndex("WeddingPlanId");

                    b.ToTable("Limousines");
                });

            modelBuilder.Entity("Paraglider.AspNetCore.Identity.Domain.Entities.Media", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AlbumId")
                        .HasColumnType("uuid");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AlbumId");

                    b.ToTable("Medias");
                });

            modelBuilder.Entity("Paraglider.AspNetCore.Identity.Domain.Entities.Payment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<decimal?>("Sum")
                        .HasColumnType("numeric");

                    b.Property<Guid?>("WPItemDescId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("WPItemDescId");

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("Paraglider.AspNetCore.Identity.Domain.Entities.PhotoStudio", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AlbumId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CityId")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("WeddingPlanId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AlbumId");

                    b.HasIndex("CityId");

                    b.HasIndex("WeddingPlanId");

                    b.ToTable("PhotoStudios");
                });

            modelBuilder.Entity("Paraglider.AspNetCore.Identity.Domain.Entities.Photographer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AlbumId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CityId")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("WeddingPlanId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AlbumId");

                    b.HasIndex("CityId");

                    b.HasIndex("WeddingPlanId");

                    b.ToTable("Photographers");
                });

            modelBuilder.Entity("Paraglider.AspNetCore.Identity.Domain.Entities.Premise", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AlbumId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("BanquetHallId")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<decimal?>("MinimalPrice")
                        .HasColumnType("numeric");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AlbumId");

                    b.HasIndex("BanquetHallId");

                    b.ToTable("Premises");
                });

            modelBuilder.Entity("Paraglider.AspNetCore.Identity.Domain.Entities.Review", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("AvatarUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("BanquetHallId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CateringId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("DecoratorId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("DjId")
                        .HasColumnType("uuid");

                    b.Property<double>("Evaluation")
                        .HasColumnType("double precision");

                    b.Property<Guid?>("LimousineId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("PhotoStudioId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("PhotographerId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("StylistId")
                        .HasColumnType("uuid");

                    b.Property<string>("Text")
                        .HasColumnType("text");

                    b.Property<Guid?>("VideographerId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("WeddingCakeId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("WeddingHostId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("WeddingRegistrarId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("BanquetHallId");

                    b.HasIndex("CateringId");

                    b.HasIndex("DecoratorId");

                    b.HasIndex("DjId");

                    b.HasIndex("LimousineId");

                    b.HasIndex("PhotoStudioId");

                    b.HasIndex("PhotographerId");

                    b.HasIndex("StylistId");

                    b.HasIndex("VideographerId");

                    b.HasIndex("WeddingCakeId");

                    b.HasIndex("WeddingHostId");

                    b.HasIndex("WeddingRegistrarId");

                    b.ToTable("Reviews");
                });

            modelBuilder.Entity("Paraglider.AspNetCore.Identity.Domain.Entities.Stylist", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AlbumId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CityId")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("WeddingPlanId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AlbumId");

                    b.HasIndex("CityId");

                    b.HasIndex("WeddingPlanId");

                    b.ToTable("Stylists");
                });

            modelBuilder.Entity("Paraglider.AspNetCore.Identity.Domain.Entities.TempExternalInfo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ApplicationUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ExternalProvider")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasAlternateKey("ExternalProvider", "ExternalId");

                    b.HasIndex("ApplicationUserId");

                    b.ToTable("ExternalInfo");
                });

            modelBuilder.Entity("Paraglider.AspNetCore.Identity.Domain.Entities.Videographer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AlbumId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CityId")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("WeddingPlanId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AlbumId");

                    b.HasIndex("CityId");

                    b.HasIndex("WeddingPlanId");

                    b.ToTable("Videographers");
                });

            modelBuilder.Entity("Paraglider.AspNetCore.Identity.Domain.Entities.WPItemDesc", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ConfigurationItemId")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("WPItemDescs");
                });

            modelBuilder.Entity("Paraglider.AspNetCore.Identity.Domain.Entities.WeddingCake", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AlbumId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CityId")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("WeddingPlanId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AlbumId");

                    b.HasIndex("CityId");

                    b.HasIndex("WeddingPlanId");

                    b.ToTable("WeddingCakes");
                });

            modelBuilder.Entity("Paraglider.AspNetCore.Identity.Domain.Entities.WeddingHost", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AlbumId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CityId")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("WeddingPlanId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AlbumId");

                    b.HasIndex("CityId");

                    b.HasIndex("WeddingPlanId");

                    b.ToTable("WeddingHosts");
                });

            modelBuilder.Entity("Paraglider.AspNetCore.Identity.Domain.Entities.WeddingPlan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ApplicationUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CityId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationUserId");

                    b.ToTable("WeddingPlans");
                });

            modelBuilder.Entity("Paraglider.AspNetCore.Identity.Domain.Entities.WeddingRegistrar", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AlbumId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CityId")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("WeddingPlanId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AlbumId");

                    b.HasIndex("CityId");

                    b.HasIndex("WeddingPlanId");

                    b.ToTable("WeddingRegistrars");
                });

            modelBuilder.Entity("Paraglider.AspNetCore.Identity.Domain.Entities.WeddingService", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CateringId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("DecoratorId")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<Guid?>("DjId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("PhotoStudioId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("PhotographerId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("StylistId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("VideographerId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("WeddingCakeId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("WeddingHostId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("WeddingRegistrarId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CateringId");

                    b.HasIndex("DecoratorId");

                    b.HasIndex("DjId");

                    b.HasIndex("PhotoStudioId");

                    b.HasIndex("PhotographerId");

                    b.HasIndex("StylistId");

                    b.HasIndex("VideographerId");

                    b.HasIndex("WeddingCakeId");

                    b.HasIndex("WeddingHostId");

                    b.HasIndex("WeddingRegistrarId");

                    b.ToTable("WeddingServices");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("Paraglider.AspNetCore.Identity.Domain.Entities.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("Paraglider.AspNetCore.Identity.Domain.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("Paraglider.AspNetCore.Identity.Domain.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("Paraglider.AspNetCore.Identity.Domain.Entities.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Paraglider.AspNetCore.Identity.Domain.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("Paraglider.AspNetCore.Identity.Domain.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Paraglider.AspNetCore.Identity.Domain.Entities.ApplicationUser", b =>
                {
                    b.HasOne("Paraglider.AspNetCore.Identity.Domain.Entities.City", "City")
                        .WithMany()
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("City");
                });

            modelBuilder.Entity("Paraglider.AspNetCore.Identity.Domain.Entities.BanquetHall", b =>
                {
                    b.HasOne("Paraglider.AspNetCore.Identity.Domain.Entities.Album", "Album")
                        .WithMany()
                        .HasForeignKey("AlbumId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Paraglider.AspNetCore.Identity.Domain.Entities.City", "City")
                        .WithMany()
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Paraglider.AspNetCore.Identity.Domain.Entities.WeddingPlan", null)
                        .WithMany("BanquetHalls")
                        .HasForeignKey("WeddingPlanId");

                    b.OwnsOne("Paraglider.AspNetCore.Identity.Domain.ValueObjects.Contacts", "Contacts", b1 =>
                        {
                            b1.Property<Guid>("BanquetHallId")
                                .HasColumnType("uuid");

                            b1.Property<string>("PhoneNumber")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("PhoneNumber");

                            b1.HasKey("BanquetHallId");

                            b1.ToTable("BanquetHalls");

                            b1.WithOwner()
                                .HasForeignKey("BanquetHallId");
                        });

                    b.OwnsOne("Paraglider.AspNetCore.Identity.Domain.ValueObjects.ExternalInfo", "ExternalInfo", b1 =>
                        {
                            b1.Property<Guid>("BanquetHallId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Id")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("ExternalId");

                            b1.Property<int>("Provider")
                                .HasColumnType("integer")
                                .HasColumnName("Provider");

                            b1.HasKey("BanquetHallId");

                            b1.ToTable("BanquetHalls");

                            b1.WithOwner()
                                .HasForeignKey("BanquetHallId");
                        });

                    b.Navigation("Album");

                    b.Navigation("City");

                    b.Navigation("Contacts")
                        .IsRequired();

                    b.Navigation("ExternalInfo")
                        .IsRequired();
                });

            modelBuilder.Entity("Paraglider.AspNetCore.Identity.Domain.Entities.Category", b =>
                {
                    b.HasOne("Paraglider.AspNetCore.Identity.Domain.Entities.WeddingPlan", null)
                        .WithMany("UsedCategories")
                        .HasForeignKey("WeddingPlanId");
                });

            modelBuilder.Entity("Paraglider.AspNetCore.Identity.Domain.Entities.Catering", b =>
                {
                    b.HasOne("Paraglider.AspNetCore.Identity.Domain.Entities.Album", "Album")
                        .WithMany()
                        .HasForeignKey("AlbumId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Paraglider.AspNetCore.Identity.Domain.Entities.City", "City")
                        .WithMany()
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Paraglider.AspNetCore.Identity.Domain.Entities.WeddingPlan", null)
                        .WithMany("Caterings")
                        .HasForeignKey("WeddingPlanId");

                    b.OwnsOne("Paraglider.AspNetCore.Identity.Domain.ValueObjects.Contacts", "Contacts", b1 =>
                        {
                            b1.Property<Guid>("CateringId")
                                .HasColumnType("uuid");

                            b1.Property<string>("PhoneNumber")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("PhoneNumber");

                            b1.HasKey("CateringId");

                            b1.ToTable("Caterings");

                            b1.WithOwner()
                                .HasForeignKey("CateringId");
                        });

                    b.OwnsOne("Paraglider.AspNetCore.Identity.Domain.ValueObjects.ExternalInfo", "ExternalInfo", b1 =>
                        {
                            b1.Property<Guid>("CateringId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Id")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("ExternalId");

                            b1.Property<int>("Provider")
                                .HasColumnType("integer")
                                .HasColumnName("Provider");

                            b1.HasKey("CateringId");

                            b1.ToTable("Caterings");

                            b1.WithOwner()
                                .HasForeignKey("CateringId");
                        });

                    b.Navigation("Album");

                    b.Navigation("City");

                    b.Navigation("Contacts")
                        .IsRequired();

                    b.Navigation("ExternalInfo")
                        .IsRequired();
                });

            modelBuilder.Entity("Paraglider.AspNetCore.Identity.Domain.Entities.Decorator", b =>
                {
                    b.HasOne("Paraglider.AspNetCore.Identity.Domain.Entities.Album", "Album")
                        .WithMany()
                        .HasForeignKey("AlbumId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Paraglider.AspNetCore.Identity.Domain.Entities.City", "City")
                        .WithMany()
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Paraglider.AspNetCore.Identity.Domain.Entities.WeddingPlan", null)
                        .WithMany("Decorators")
                        .HasForeignKey("WeddingPlanId");

                    b.OwnsOne("Paraglider.AspNetCore.Identity.Domain.ValueObjects.Contacts", "Contacts", b1 =>
                        {
                            b1.Property<Guid>("DecoratorId")
                                .HasColumnType("uuid");

                            b1.Property<string>("PhoneNumber")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("PhoneNumber");

                            b1.HasKey("DecoratorId");

                            b1.ToTable("Decorators");

                            b1.WithOwner()
                                .HasForeignKey("DecoratorId");
                        });

                    b.OwnsOne("Paraglider.AspNetCore.Identity.Domain.ValueObjects.ExternalInfo", "ExternalInfo", b1 =>
                        {
                            b1.Property<Guid>("DecoratorId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Id")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("ExternalId");

                            b1.Property<int>("Provider")
                                .HasColumnType("integer")
                                .HasColumnName("Provider");

                            b1.HasKey("DecoratorId");

                            b1.ToTable("Decorators");

                            b1.WithOwner()
                                .HasForeignKey("DecoratorId");
                        });

                    b.Navigation("Album");

                    b.Navigation("City");

                    b.Navigation("Contacts")
                        .IsRequired();

                    b.Navigation("ExternalInfo")
                        .IsRequired();
                });

            modelBuilder.Entity("Paraglider.AspNetCore.Identity.Domain.Entities.Dj", b =>
                {
                    b.HasOne("Paraglider.AspNetCore.Identity.Domain.Entities.Album", "Album")
                        .WithMany()
                        .HasForeignKey("AlbumId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Paraglider.AspNetCore.Identity.Domain.Entities.City", "City")
                        .WithMany()
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Paraglider.AspNetCore.Identity.Domain.Entities.WeddingPlan", null)
                        .WithMany("Djs")
                        .HasForeignKey("WeddingPlanId");

                    b.OwnsOne("Paraglider.AspNetCore.Identity.Domain.ValueObjects.Contacts", "Contacts", b1 =>
                        {
                            b1.Property<Guid>("DjId")
                                .HasColumnType("uuid");

                            b1.Property<string>("PhoneNumber")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("PhoneNumber");

                            b1.HasKey("DjId");

                            b1.ToTable("Djs");

                            b1.WithOwner()
                                .HasForeignKey("DjId");
                        });

                    b.OwnsOne("Paraglider.AspNetCore.Identity.Domain.ValueObjects.ExternalInfo", "ExternalInfo", b1 =>
                        {
                            b1.Property<Guid>("DjId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Id")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("ExternalId");

                            b1.Property<int>("Provider")
                                .HasColumnType("integer")
                                .HasColumnName("Provider");

                            b1.HasKey("DjId");

                            b1.ToTable("Djs");

                            b1.WithOwner()
                                .HasForeignKey("DjId");
                        });

                    b.Navigation("Album");

                    b.Navigation("City");

                    b.Navigation("Contacts")
                        .IsRequired();

                    b.Navigation("ExternalInfo")
                        .IsRequired();
                });

            modelBuilder.Entity("Paraglider.AspNetCore.Identity.Domain.Entities.Limousine", b =>
                {
                    b.HasOne("Paraglider.AspNetCore.Identity.Domain.Entities.Album", "Album")
                        .WithMany()
                        .HasForeignKey("AlbumId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Paraglider.AspNetCore.Identity.Domain.Entities.City", "City")
                        .WithMany()
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Paraglider.AspNetCore.Identity.Domain.Entities.WeddingPlan", null)
                        .WithMany("Limousines")
                        .HasForeignKey("WeddingPlanId");

                    b.OwnsOne("Paraglider.AspNetCore.Identity.Domain.ValueObjects.Contacts", "Contacts", b1 =>
                        {
                            b1.Property<Guid>("LimousineId")
                                .HasColumnType("uuid");

                            b1.Property<string>("PhoneNumber")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("PhoneNumber");

                            b1.HasKey("LimousineId");

                            b1.ToTable("Limousines");

                            b1.WithOwner()
                                .HasForeignKey("LimousineId");
                        });

                    b.OwnsOne("Paraglider.AspNetCore.Identity.Domain.ValueObjects.ExternalInfo", "ExternalInfo", b1 =>
                        {
                            b1.Property<Guid>("LimousineId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Id")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("ExternalId");

                            b1.Property<int>("Provider")
                                .HasColumnType("integer")
                                .HasColumnName("Provider");

                            b1.HasKey("LimousineId");

                            b1.ToTable("Limousines");

                            b1.WithOwner()
                                .HasForeignKey("LimousineId");
                        });

                    b.Navigation("Album");

                    b.Navigation("City");

                    b.Navigation("Contacts")
                        .IsRequired();

                    b.Navigation("ExternalInfo")
                        .IsRequired();
                });

            modelBuilder.Entity("Paraglider.AspNetCore.Identity.Domain.Entities.Media", b =>
                {
                    b.HasOne("Paraglider.AspNetCore.Identity.Domain.Entities.Album", null)
                        .WithMany("Media")
                        .HasForeignKey("AlbumId");
                });

            modelBuilder.Entity("Paraglider.AspNetCore.Identity.Domain.Entities.Payment", b =>
                {
                    b.HasOne("Paraglider.AspNetCore.Identity.Domain.Entities.WPItemDesc", null)
                        .WithMany("Payments")
                        .HasForeignKey("WPItemDescId");
                });

            modelBuilder.Entity("Paraglider.AspNetCore.Identity.Domain.Entities.PhotoStudio", b =>
                {
                    b.HasOne("Paraglider.AspNetCore.Identity.Domain.Entities.Album", "Album")
                        .WithMany()
                        .HasForeignKey("AlbumId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Paraglider.AspNetCore.Identity.Domain.Entities.City", "City")
                        .WithMany()
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Paraglider.AspNetCore.Identity.Domain.Entities.WeddingPlan", null)
                        .WithMany("PhotoStudios")
                        .HasForeignKey("WeddingPlanId");

                    b.OwnsOne("Paraglider.AspNetCore.Identity.Domain.ValueObjects.Contacts", "Contacts", b1 =>
                        {
                            b1.Property<Guid>("PhotoStudioId")
                                .HasColumnType("uuid");

                            b1.Property<string>("PhoneNumber")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("PhoneNumber");

                            b1.HasKey("PhotoStudioId");

                            b1.ToTable("PhotoStudios");

                            b1.WithOwner()
                                .HasForeignKey("PhotoStudioId");
                        });

                    b.OwnsOne("Paraglider.AspNetCore.Identity.Domain.ValueObjects.ExternalInfo", "ExternalInfo", b1 =>
                        {
                            b1.Property<Guid>("PhotoStudioId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Id")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("ExternalId");

                            b1.Property<int>("Provider")
                                .HasColumnType("integer")
                                .HasColumnName("Provider");

                            b1.HasKey("PhotoStudioId");

                            b1.ToTable("PhotoStudios");

                            b1.WithOwner()
                                .HasForeignKey("PhotoStudioId");
                        });

                    b.Navigation("Album");

                    b.Navigation("City");

                    b.Navigation("Contacts")
                        .IsRequired();

                    b.Navigation("ExternalInfo")
                        .IsRequired();
                });

            modelBuilder.Entity("Paraglider.AspNetCore.Identity.Domain.Entities.Photographer", b =>
                {
                    b.HasOne("Paraglider.AspNetCore.Identity.Domain.Entities.Album", "Album")
                        .WithMany()
                        .HasForeignKey("AlbumId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Paraglider.AspNetCore.Identity.Domain.Entities.City", "City")
                        .WithMany()
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Paraglider.AspNetCore.Identity.Domain.Entities.WeddingPlan", null)
                        .WithMany("Photographers")
                        .HasForeignKey("WeddingPlanId");

                    b.OwnsOne("Paraglider.AspNetCore.Identity.Domain.ValueObjects.Contacts", "Contacts", b1 =>
                        {
                            b1.Property<Guid>("PhotographerId")
                                .HasColumnType("uuid");

                            b1.Property<string>("PhoneNumber")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("PhoneNumber");

                            b1.HasKey("PhotographerId");

                            b1.ToTable("Photographers");

                            b1.WithOwner()
                                .HasForeignKey("PhotographerId");
                        });

                    b.OwnsOne("Paraglider.AspNetCore.Identity.Domain.ValueObjects.ExternalInfo", "ExternalInfo", b1 =>
                        {
                            b1.Property<Guid>("PhotographerId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Id")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("ExternalId");

                            b1.Property<int>("Provider")
                                .HasColumnType("integer")
                                .HasColumnName("Provider");

                            b1.HasKey("PhotographerId");

                            b1.ToTable("Photographers");

                            b1.WithOwner()
                                .HasForeignKey("PhotographerId");
                        });

                    b.Navigation("Album");

                    b.Navigation("City");

                    b.Navigation("Contacts")
                        .IsRequired();

                    b.Navigation("ExternalInfo")
                        .IsRequired();
                });

            modelBuilder.Entity("Paraglider.AspNetCore.Identity.Domain.Entities.Premise", b =>
                {
                    b.HasOne("Paraglider.AspNetCore.Identity.Domain.Entities.Album", "Album")
                        .WithMany()
                        .HasForeignKey("AlbumId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Paraglider.AspNetCore.Identity.Domain.Entities.BanquetHall", null)
                        .WithMany("Premises")
                        .HasForeignKey("BanquetHallId");

                    b.OwnsOne("Paraglider.AspNetCore.Identity.Domain.ValueObjects.Capacity", "Capacity", b1 =>
                        {
                            b1.Property<Guid>("PremiseId")
                                .HasColumnType("uuid");

                            b1.Property<int?>("Max")
                                .HasColumnType("integer")
                                .HasColumnName("MaxCapacity");

                            b1.Property<int?>("Min")
                                .HasColumnType("integer")
                                .HasColumnName("MinCapacity");

                            b1.HasKey("PremiseId");

                            b1.ToTable("Premises");

                            b1.WithOwner()
                                .HasForeignKey("PremiseId");
                        });

                    b.OwnsOne("Paraglider.AspNetCore.Identity.Domain.ValueObjects.PremiseRentalPrice", "RentalPrice", b1 =>
                        {
                            b1.Property<Guid>("PremiseId")
                                .HasColumnType("uuid");

                            b1.Property<decimal?>("PricePerPerson")
                                .HasColumnType("numeric")
                                .HasColumnName("RentalPricePerPerson");

                            b1.Property<decimal?>("RentalPrice")
                                .HasColumnType("numeric")
                                .HasColumnName("RentalPrice");

                            b1.HasKey("PremiseId");

                            b1.ToTable("Premises");

                            b1.WithOwner()
                                .HasForeignKey("PremiseId");
                        });

                    b.Navigation("Album");

                    b.Navigation("Capacity")
                        .IsRequired();

                    b.Navigation("RentalPrice")
                        .IsRequired();
                });

            modelBuilder.Entity("Paraglider.AspNetCore.Identity.Domain.Entities.Review", b =>
                {
                    b.HasOne("Paraglider.AspNetCore.Identity.Domain.Entities.BanquetHall", null)
                        .WithMany("Reviews")
                        .HasForeignKey("BanquetHallId");

                    b.HasOne("Paraglider.AspNetCore.Identity.Domain.Entities.Catering", null)
                        .WithMany("Reviews")
                        .HasForeignKey("CateringId");

                    b.HasOne("Paraglider.AspNetCore.Identity.Domain.Entities.Decorator", null)
                        .WithMany("Reviews")
                        .HasForeignKey("DecoratorId");

                    b.HasOne("Paraglider.AspNetCore.Identity.Domain.Entities.Dj", null)
                        .WithMany("Reviews")
                        .HasForeignKey("DjId");

                    b.HasOne("Paraglider.AspNetCore.Identity.Domain.Entities.Limousine", null)
                        .WithMany("Reviews")
                        .HasForeignKey("LimousineId");

                    b.HasOne("Paraglider.AspNetCore.Identity.Domain.Entities.PhotoStudio", null)
                        .WithMany("Reviews")
                        .HasForeignKey("PhotoStudioId");

                    b.HasOne("Paraglider.AspNetCore.Identity.Domain.Entities.Photographer", null)
                        .WithMany("Reviews")
                        .HasForeignKey("PhotographerId");

                    b.HasOne("Paraglider.AspNetCore.Identity.Domain.Entities.Stylist", null)
                        .WithMany("Reviews")
                        .HasForeignKey("StylistId");

                    b.HasOne("Paraglider.AspNetCore.Identity.Domain.Entities.Videographer", null)
                        .WithMany("Reviews")
                        .HasForeignKey("VideographerId");

                    b.HasOne("Paraglider.AspNetCore.Identity.Domain.Entities.WeddingCake", null)
                        .WithMany("Reviews")
                        .HasForeignKey("WeddingCakeId");

                    b.HasOne("Paraglider.AspNetCore.Identity.Domain.Entities.WeddingHost", null)
                        .WithMany("Reviews")
                        .HasForeignKey("WeddingHostId");

                    b.HasOne("Paraglider.AspNetCore.Identity.Domain.Entities.WeddingRegistrar", null)
                        .WithMany("Reviews")
                        .HasForeignKey("WeddingRegistrarId");
                });

            modelBuilder.Entity("Paraglider.AspNetCore.Identity.Domain.Entities.Stylist", b =>
                {
                    b.HasOne("Paraglider.AspNetCore.Identity.Domain.Entities.Album", "Album")
                        .WithMany()
                        .HasForeignKey("AlbumId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Paraglider.AspNetCore.Identity.Domain.Entities.City", "City")
                        .WithMany()
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Paraglider.AspNetCore.Identity.Domain.Entities.WeddingPlan", null)
                        .WithMany("Stylists")
                        .HasForeignKey("WeddingPlanId");

                    b.OwnsOne("Paraglider.AspNetCore.Identity.Domain.ValueObjects.Contacts", "Contacts", b1 =>
                        {
                            b1.Property<Guid>("StylistId")
                                .HasColumnType("uuid");

                            b1.Property<string>("PhoneNumber")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("PhoneNumber");

                            b1.HasKey("StylistId");

                            b1.ToTable("Stylists");

                            b1.WithOwner()
                                .HasForeignKey("StylistId");
                        });

                    b.OwnsOne("Paraglider.AspNetCore.Identity.Domain.ValueObjects.ExternalInfo", "ExternalInfo", b1 =>
                        {
                            b1.Property<Guid>("StylistId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Id")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("ExternalId");

                            b1.Property<int>("Provider")
                                .HasColumnType("integer")
                                .HasColumnName("Provider");

                            b1.HasKey("StylistId");

                            b1.ToTable("Stylists");

                            b1.WithOwner()
                                .HasForeignKey("StylistId");
                        });

                    b.Navigation("Album");

                    b.Navigation("City");

                    b.Navigation("Contacts")
                        .IsRequired();

                    b.Navigation("ExternalInfo")
                        .IsRequired();
                });

            modelBuilder.Entity("Paraglider.AspNetCore.Identity.Domain.Entities.TempExternalInfo", b =>
                {
                    b.HasOne("Paraglider.AspNetCore.Identity.Domain.Entities.ApplicationUser", null)
                        .WithMany("ExternalInfo")
                        .HasForeignKey("ApplicationUserId");
                });

            modelBuilder.Entity("Paraglider.AspNetCore.Identity.Domain.Entities.Videographer", b =>
                {
                    b.HasOne("Paraglider.AspNetCore.Identity.Domain.Entities.Album", "Album")
                        .WithMany()
                        .HasForeignKey("AlbumId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Paraglider.AspNetCore.Identity.Domain.Entities.City", "City")
                        .WithMany()
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Paraglider.AspNetCore.Identity.Domain.Entities.WeddingPlan", null)
                        .WithMany("Videographers")
                        .HasForeignKey("WeddingPlanId");

                    b.OwnsOne("Paraglider.AspNetCore.Identity.Domain.ValueObjects.Contacts", "Contacts", b1 =>
                        {
                            b1.Property<Guid>("VideographerId")
                                .HasColumnType("uuid");

                            b1.Property<string>("PhoneNumber")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("PhoneNumber");

                            b1.HasKey("VideographerId");

                            b1.ToTable("Videographers");

                            b1.WithOwner()
                                .HasForeignKey("VideographerId");
                        });

                    b.OwnsOne("Paraglider.AspNetCore.Identity.Domain.ValueObjects.ExternalInfo", "ExternalInfo", b1 =>
                        {
                            b1.Property<Guid>("VideographerId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Id")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("ExternalId");

                            b1.Property<int>("Provider")
                                .HasColumnType("integer")
                                .HasColumnName("Provider");

                            b1.HasKey("VideographerId");

                            b1.ToTable("Videographers");

                            b1.WithOwner()
                                .HasForeignKey("VideographerId");
                        });

                    b.Navigation("Album");

                    b.Navigation("City");

                    b.Navigation("Contacts")
                        .IsRequired();

                    b.Navigation("ExternalInfo")
                        .IsRequired();
                });

            modelBuilder.Entity("Paraglider.AspNetCore.Identity.Domain.Entities.WPItemDesc", b =>
                {
                    b.OwnsOne("Paraglider.AspNetCore.Identity.Domain.ValueObjects.Time", "TimeData", b1 =>
                        {
                            b1.Property<Guid>("WPItemDescId")
                                .HasColumnType("uuid");

                            b1.Property<int>("Type")
                                .HasColumnType("integer");

                            b1.HasKey("WPItemDescId");

                            b1.ToTable("WPItemDescs");

                            b1.WithOwner()
                                .HasForeignKey("WPItemDescId");

                            b1.OwnsOne("Paraglider.AspNetCore.Identity.Domain.ValueObjects.TimeOfDay", "ExactTime", b2 =>
                                {
                                    b2.Property<Guid>("TimeWPItemDescId")
                                        .HasColumnType("uuid");

                                    b2.Property<int>("Hour")
                                        .HasColumnType("integer")
                                        .HasColumnName("ExactTime_Hour");

                                    b2.Property<int>("Minute")
                                        .HasColumnType("integer")
                                        .HasColumnName("ExactTime_Minute");

                                    b2.Property<int>("Second")
                                        .HasColumnType("integer")
                                        .HasColumnName("ExactTime_Second");

                                    b2.HasKey("TimeWPItemDescId");

                                    b2.ToTable("WPItemDescs");

                                    b2.WithOwner()
                                        .HasForeignKey("TimeWPItemDescId");
                                });

                            b1.OwnsOne("Paraglider.AspNetCore.Identity.Domain.ValueObjects.TimeOfDay", "IntervalEnd", b2 =>
                                {
                                    b2.Property<Guid>("TimeWPItemDescId")
                                        .HasColumnType("uuid");

                                    b2.Property<int>("Hour")
                                        .HasColumnType("integer")
                                        .HasColumnName("IntervalEnd_Hour");

                                    b2.Property<int>("Minute")
                                        .HasColumnType("integer")
                                        .HasColumnName("IntervalEnd_Minute");

                                    b2.Property<int>("Second")
                                        .HasColumnType("integer")
                                        .HasColumnName("IntervalEnd_Second");

                                    b2.HasKey("TimeWPItemDescId");

                                    b2.ToTable("WPItemDescs");

                                    b2.WithOwner()
                                        .HasForeignKey("TimeWPItemDescId");
                                });

                            b1.OwnsOne("Paraglider.AspNetCore.Identity.Domain.ValueObjects.TimeOfDay", "IntervalStart", b2 =>
                                {
                                    b2.Property<Guid>("TimeWPItemDescId")
                                        .HasColumnType("uuid");

                                    b2.Property<int>("Hour")
                                        .HasColumnType("integer")
                                        .HasColumnName("IntervalStart_Hour");

                                    b2.Property<int>("Minute")
                                        .HasColumnType("integer")
                                        .HasColumnName("IntervalStart_Minute");

                                    b2.Property<int>("Second")
                                        .HasColumnType("integer")
                                        .HasColumnName("IntervalStart_Second");

                                    b2.HasKey("TimeWPItemDescId");

                                    b2.ToTable("WPItemDescs");

                                    b2.WithOwner()
                                        .HasForeignKey("TimeWPItemDescId");
                                });

                            b1.Navigation("ExactTime");

                            b1.Navigation("IntervalEnd");

                            b1.Navigation("IntervalStart");
                        });

                    b.Navigation("TimeData")
                        .IsRequired();
                });

            modelBuilder.Entity("Paraglider.AspNetCore.Identity.Domain.Entities.WeddingCake", b =>
                {
                    b.HasOne("Paraglider.AspNetCore.Identity.Domain.Entities.Album", "Album")
                        .WithMany()
                        .HasForeignKey("AlbumId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Paraglider.AspNetCore.Identity.Domain.Entities.City", "City")
                        .WithMany()
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Paraglider.AspNetCore.Identity.Domain.Entities.WeddingPlan", null)
                        .WithMany("WeddingCakes")
                        .HasForeignKey("WeddingPlanId");

                    b.OwnsOne("Paraglider.AspNetCore.Identity.Domain.ValueObjects.Contacts", "Contacts", b1 =>
                        {
                            b1.Property<Guid>("WeddingCakeId")
                                .HasColumnType("uuid");

                            b1.Property<string>("PhoneNumber")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("PhoneNumber");

                            b1.HasKey("WeddingCakeId");

                            b1.ToTable("WeddingCakes");

                            b1.WithOwner()
                                .HasForeignKey("WeddingCakeId");
                        });

                    b.OwnsOne("Paraglider.AspNetCore.Identity.Domain.ValueObjects.ExternalInfo", "ExternalInfo", b1 =>
                        {
                            b1.Property<Guid>("WeddingCakeId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Id")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("ExternalId");

                            b1.Property<int>("Provider")
                                .HasColumnType("integer")
                                .HasColumnName("Provider");

                            b1.HasKey("WeddingCakeId");

                            b1.ToTable("WeddingCakes");

                            b1.WithOwner()
                                .HasForeignKey("WeddingCakeId");
                        });

                    b.Navigation("Album");

                    b.Navigation("City");

                    b.Navigation("Contacts")
                        .IsRequired();

                    b.Navigation("ExternalInfo")
                        .IsRequired();
                });

            modelBuilder.Entity("Paraglider.AspNetCore.Identity.Domain.Entities.WeddingHost", b =>
                {
                    b.HasOne("Paraglider.AspNetCore.Identity.Domain.Entities.Album", "Album")
                        .WithMany()
                        .HasForeignKey("AlbumId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Paraglider.AspNetCore.Identity.Domain.Entities.City", "City")
                        .WithMany()
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Paraglider.AspNetCore.Identity.Domain.Entities.WeddingPlan", null)
                        .WithMany("WeddingHosts")
                        .HasForeignKey("WeddingPlanId");

                    b.OwnsOne("Paraglider.AspNetCore.Identity.Domain.ValueObjects.Contacts", "Contacts", b1 =>
                        {
                            b1.Property<Guid>("WeddingHostId")
                                .HasColumnType("uuid");

                            b1.Property<string>("PhoneNumber")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("PhoneNumber");

                            b1.HasKey("WeddingHostId");

                            b1.ToTable("WeddingHosts");

                            b1.WithOwner()
                                .HasForeignKey("WeddingHostId");
                        });

                    b.OwnsOne("Paraglider.AspNetCore.Identity.Domain.ValueObjects.ExternalInfo", "ExternalInfo", b1 =>
                        {
                            b1.Property<Guid>("WeddingHostId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Id")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("ExternalId");

                            b1.Property<int>("Provider")
                                .HasColumnType("integer")
                                .HasColumnName("Provider");

                            b1.HasKey("WeddingHostId");

                            b1.ToTable("WeddingHosts");

                            b1.WithOwner()
                                .HasForeignKey("WeddingHostId");
                        });

                    b.Navigation("Album");

                    b.Navigation("City");

                    b.Navigation("Contacts")
                        .IsRequired();

                    b.Navigation("ExternalInfo")
                        .IsRequired();
                });

            modelBuilder.Entity("Paraglider.AspNetCore.Identity.Domain.Entities.WeddingPlan", b =>
                {
                    b.HasOne("Paraglider.AspNetCore.Identity.Domain.Entities.ApplicationUser", null)
                        .WithMany("Plans")
                        .HasForeignKey("ApplicationUserId");
                });

            modelBuilder.Entity("Paraglider.AspNetCore.Identity.Domain.Entities.WeddingRegistrar", b =>
                {
                    b.HasOne("Paraglider.AspNetCore.Identity.Domain.Entities.Album", "Album")
                        .WithMany()
                        .HasForeignKey("AlbumId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Paraglider.AspNetCore.Identity.Domain.Entities.City", "City")
                        .WithMany()
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Paraglider.AspNetCore.Identity.Domain.Entities.WeddingPlan", null)
                        .WithMany("Registrars")
                        .HasForeignKey("WeddingPlanId");

                    b.OwnsOne("Paraglider.AspNetCore.Identity.Domain.ValueObjects.Contacts", "Contacts", b1 =>
                        {
                            b1.Property<Guid>("WeddingRegistrarId")
                                .HasColumnType("uuid");

                            b1.Property<string>("PhoneNumber")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("PhoneNumber");

                            b1.HasKey("WeddingRegistrarId");

                            b1.ToTable("WeddingRegistrars");

                            b1.WithOwner()
                                .HasForeignKey("WeddingRegistrarId");
                        });

                    b.OwnsOne("Paraglider.AspNetCore.Identity.Domain.ValueObjects.ExternalInfo", "ExternalInfo", b1 =>
                        {
                            b1.Property<Guid>("WeddingRegistrarId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Id")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("ExternalId");

                            b1.Property<int>("Provider")
                                .HasColumnType("integer")
                                .HasColumnName("Provider");

                            b1.HasKey("WeddingRegistrarId");

                            b1.ToTable("WeddingRegistrars");

                            b1.WithOwner()
                                .HasForeignKey("WeddingRegistrarId");
                        });

                    b.Navigation("Album");

                    b.Navigation("City");

                    b.Navigation("Contacts")
                        .IsRequired();

                    b.Navigation("ExternalInfo")
                        .IsRequired();
                });

            modelBuilder.Entity("Paraglider.AspNetCore.Identity.Domain.Entities.WeddingService", b =>
                {
                    b.HasOne("Paraglider.AspNetCore.Identity.Domain.Entities.Catering", null)
                        .WithMany("WeddingServices")
                        .HasForeignKey("CateringId");

                    b.HasOne("Paraglider.AspNetCore.Identity.Domain.Entities.Decorator", null)
                        .WithMany("WeddingServices")
                        .HasForeignKey("DecoratorId");

                    b.HasOne("Paraglider.AspNetCore.Identity.Domain.Entities.Dj", null)
                        .WithMany("WeddingServices")
                        .HasForeignKey("DjId");

                    b.HasOne("Paraglider.AspNetCore.Identity.Domain.Entities.PhotoStudio", null)
                        .WithMany("WeddingServices")
                        .HasForeignKey("PhotoStudioId");

                    b.HasOne("Paraglider.AspNetCore.Identity.Domain.Entities.Photographer", null)
                        .WithMany("WeddingServices")
                        .HasForeignKey("PhotographerId");

                    b.HasOne("Paraglider.AspNetCore.Identity.Domain.Entities.Stylist", null)
                        .WithMany("WeddingServices")
                        .HasForeignKey("StylistId");

                    b.HasOne("Paraglider.AspNetCore.Identity.Domain.Entities.Videographer", null)
                        .WithMany("WeddingServices")
                        .HasForeignKey("VideographerId");

                    b.HasOne("Paraglider.AspNetCore.Identity.Domain.Entities.WeddingCake", null)
                        .WithMany("WeddingServices")
                        .HasForeignKey("WeddingCakeId");

                    b.HasOne("Paraglider.AspNetCore.Identity.Domain.Entities.WeddingHost", null)
                        .WithMany("WeddingServices")
                        .HasForeignKey("WeddingHostId");

                    b.HasOne("Paraglider.AspNetCore.Identity.Domain.Entities.WeddingRegistrar", null)
                        .WithMany("WeddingServices")
                        .HasForeignKey("WeddingRegistrarId");

                    b.OwnsOne("Paraglider.AspNetCore.Identity.Domain.ValueObjects.Price", "Price", b1 =>
                        {
                            b1.Property<Guid>("WeddingServiceId")
                                .HasColumnType("uuid");

                            b1.Property<decimal?>("Max")
                                .HasColumnType("numeric")
                                .HasColumnName("MaxPrice");

                            b1.Property<decimal?>("Min")
                                .HasColumnType("numeric")
                                .HasColumnName("MinPrice");

                            b1.HasKey("WeddingServiceId");

                            b1.ToTable("WeddingServices");

                            b1.WithOwner()
                                .HasForeignKey("WeddingServiceId");
                        });

                    b.Navigation("Price")
                        .IsRequired();
                });

            modelBuilder.Entity("Paraglider.AspNetCore.Identity.Domain.Entities.Album", b =>
                {
                    b.Navigation("Media");
                });

            modelBuilder.Entity("Paraglider.AspNetCore.Identity.Domain.Entities.ApplicationUser", b =>
                {
                    b.Navigation("ExternalInfo");

                    b.Navigation("Plans");
                });

            modelBuilder.Entity("Paraglider.AspNetCore.Identity.Domain.Entities.BanquetHall", b =>
                {
                    b.Navigation("Premises");

                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("Paraglider.AspNetCore.Identity.Domain.Entities.Catering", b =>
                {
                    b.Navigation("Reviews");

                    b.Navigation("WeddingServices");
                });

            modelBuilder.Entity("Paraglider.AspNetCore.Identity.Domain.Entities.Decorator", b =>
                {
                    b.Navigation("Reviews");

                    b.Navigation("WeddingServices");
                });

            modelBuilder.Entity("Paraglider.AspNetCore.Identity.Domain.Entities.Dj", b =>
                {
                    b.Navigation("Reviews");

                    b.Navigation("WeddingServices");
                });

            modelBuilder.Entity("Paraglider.AspNetCore.Identity.Domain.Entities.Limousine", b =>
                {
                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("Paraglider.AspNetCore.Identity.Domain.Entities.PhotoStudio", b =>
                {
                    b.Navigation("Reviews");

                    b.Navigation("WeddingServices");
                });

            modelBuilder.Entity("Paraglider.AspNetCore.Identity.Domain.Entities.Photographer", b =>
                {
                    b.Navigation("Reviews");

                    b.Navigation("WeddingServices");
                });

            modelBuilder.Entity("Paraglider.AspNetCore.Identity.Domain.Entities.Stylist", b =>
                {
                    b.Navigation("Reviews");

                    b.Navigation("WeddingServices");
                });

            modelBuilder.Entity("Paraglider.AspNetCore.Identity.Domain.Entities.Videographer", b =>
                {
                    b.Navigation("Reviews");

                    b.Navigation("WeddingServices");
                });

            modelBuilder.Entity("Paraglider.AspNetCore.Identity.Domain.Entities.WPItemDesc", b =>
                {
                    b.Navigation("Payments");
                });

            modelBuilder.Entity("Paraglider.AspNetCore.Identity.Domain.Entities.WeddingCake", b =>
                {
                    b.Navigation("Reviews");

                    b.Navigation("WeddingServices");
                });

            modelBuilder.Entity("Paraglider.AspNetCore.Identity.Domain.Entities.WeddingHost", b =>
                {
                    b.Navigation("Reviews");

                    b.Navigation("WeddingServices");
                });

            modelBuilder.Entity("Paraglider.AspNetCore.Identity.Domain.Entities.WeddingPlan", b =>
                {
                    b.Navigation("BanquetHalls");

                    b.Navigation("Caterings");

                    b.Navigation("Decorators");

                    b.Navigation("Djs");

                    b.Navigation("Limousines");

                    b.Navigation("PhotoStudios");

                    b.Navigation("Photographers");

                    b.Navigation("Registrars");

                    b.Navigation("Stylists");

                    b.Navigation("UsedCategories");

                    b.Navigation("Videographers");

                    b.Navigation("WeddingCakes");

                    b.Navigation("WeddingHosts");
                });

            modelBuilder.Entity("Paraglider.AspNetCore.Identity.Domain.Entities.WeddingRegistrar", b =>
                {
                    b.Navigation("Reviews");

                    b.Navigation("WeddingServices");
                });
#pragma warning restore 612, 618
        }
    }
}
