// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.

using System.Diagnostics.CodeAnalysis;

[assembly: SuppressMessage("Usage", "CA2254:Шаблон должен быть статическим выражением", Justification = "<Ожидание>", Scope = "member", Target = "~M:Paraglider.AspNetCore.Identity.Web.Endpoints.SecurityEndpoints.Commands.ExternalAuthHandler.Handle(Paraglider.AspNetCore.Identity.Web.Endpoints.SecurityEndpoints.Commands.ExternalAuthCommand,System.Threading.CancellationToken)~System.Threading.Tasks.Task{Paraglider.AspNetCore.Identity.Infrastructure.Responses.OperationResult.OperationResult}")]
[assembly: SuppressMessage("Usage", "CA2254:Шаблон должен быть статическим выражением", Justification = "<Ожидание>", Scope = "member", Target = "~M:Paraglider.AspNetCore.Identity.Web.Endpoints.SecurityEndpoints.Queries.PostLogOutRequestHandler.Handle(Paraglider.AspNetCore.Identity.Web.Endpoints.SecurityEndpoints.Queries.PostLogOutRequest,System.Threading.CancellationToken)~System.Threading.Tasks.Task{Paraglider.AspNetCore.Identity.Infrastructure.Responses.OperationResult.OperationResult}")]
[assembly: SuppressMessage("Usage", "CA2254:Шаблон должен быть статическим выражением", Justification = "<Ожидание>", Scope = "member", Target = "~M:Paraglider.AspNetCore.Identity.Web.Endpoints.SecurityEndpoints.Commands.ExternalAuthPropertiesHandler.Handle(Paraglider.AspNetCore.Identity.Web.Endpoints.SecurityEndpoints.Commands.ExternalAuthPropertiesCommand,System.Threading.CancellationToken)~System.Threading.Tasks.Task{Paraglider.AspNetCore.Identity.Infrastructure.Responses.OperationResult.OperationResult{Microsoft.AspNetCore.Authentication.AuthenticationProperties}}")]
[assembly: SuppressMessage("Usage", "CA2254:Шаблон должен быть статическим выражением", Justification = "<Ожидание>", Scope = "member", Target = "~M:Paraglider.AspNetCore.Identity.Web.Endpoints.SecurityEndpoints.Queries.PostBasicAuthRequestHandler.Handle(Paraglider.AspNetCore.Identity.Web.Endpoints.SecurityEndpoints.Queries.PostBasicAuthRequest,System.Threading.CancellationToken)~System.Threading.Tasks.Task{Paraglider.AspNetCore.Identity.Infrastructure.Responses.OperationResult.OperationResult}")]
